const colors = require("tailwindcss/colors");

module.exports = {
  white: {
    css: {
      '--tw-prose-body': `${colors.white} !important`,
      '--tw-prose-headings': `${colors.white} !important`,
      '--tw-prose-lead': `${colors.white} !important`,
      '--tw-prose-links': `${colors.white} !important`,
      '--tw-prose-bold': `${colors.white} !important`,
      '--tw-prose-counters': `${colors.white} !important`,
      '--tw-prose-bullets': `${colors.white} !important`,
      '--tw-prose-hr': `${colors.white} !important`,
      '--tw-prose-quotes': `${colors.white} !important`,
      '--tw-prose-quote-borders': `${colors.white} !important`,
      '--tw-prose-captions': `${colors.white} !important`,
      '--tw-prose-code': `${colors.white} !important`,
      '--tw-prose-pre-code': `${colors.white} !important`,
      '--tw-prose-pre-bg': `${colors.white} !important`,
      '--tw-prose-th-borders': `${colors.white} !important`,
      '--tw-prose-td-borders': `${colors.white} !important`,
      '--tw-prose-invert-body': `${colors.white} !important`,
      '--tw-prose-invert-headings': `${colors.white} !important`,
      '--tw-prose-invert-lead': `${colors.white} !important`,
      '--tw-prose-invert-links': `${colors.white} !important`,
      '--tw-prose-invert-bold': `${colors.white} !important`,
      '--tw-prose-invert-counters': `${colors.white} !important`,
      '--tw-prose-invert-bullets': `${colors.white} !important`,
      '--tw-prose-invert-hr': `${colors.white} !important`,
      '--tw-prose-invert-quotes': `${colors.white} !important`,
      '--tw-prose-invert-quote-borders': `${colors.white} !important`,
      '--tw-prose-invert-captions': `${colors.white} !important`,
      '--tw-prose-invert-code': `${colors.white} !important`,
      '--tw-prose-invert-pre-code': `${colors.white} !important`,
      '--tw-prose-invert-pre-bg': 'rgb(255 255 255 / 50%)',
      '--tw-prose-invert-th-borders': `${colors.white} !important`,
      '--tw-prose-invert-td-borders': `${colors.white} !important`,
    },
  },
}